name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  # batch: true
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - code1-infrastructure/terraform/env/*

variables:
  - name: System.Debug
    value: true
  
stages:
  - template: templates/init-stage.yml
    parameters:
      SourceFolderScripts: 'code1-infrastructure/scripts'
      SourceFolderTerraform: 'code1-infrastructure/terraform/env'

  - template: templates/deploy-stage.yml
    parameters:
      StageName: 'dev'
      WorkingDirectory: dev
      VariablesFile1: variables.yml
      VariablesFile2: variables-dev.yml
      VariablesFile3: variables-terraform.yml
