name: $(Date:yyyyMMdd)$(Rev:.r)

  
variables:
  - template: templates/variables.yml
  
stages:
  - template: templates/test-stage.yml
    parameters:
      StageName: 'dev'
      WorkingDirectory: dev
      VariablesFile1: variables.yml
      VariablesFile2: variables-dev.yml
      Env: 
        TF_VAR_EVENTSTORE_YODA_PASSWORD: $(EventStore_YodaPassword)
