apiVersion: v1
kind: ConfigMap
metadata:
  name: home-config
  namespace: code1
data:
  API_PATH_BASE: code1/home
  Home__SwaggerUiUri: /code1/swagger/index.html
  Home__HealthUiUri: /code1/health
  Home__HelloUri: /code1/hello
  Home__Proj1Uri: /code1/proj1
  Home__Proj2Uri: /code1/proj2
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: code1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: code1-home
        image: tboeker/code1-home
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: home-config
        - configMapRef:
            name: code1-config

---

apiVersion: v1
kind: Service
metadata:
  name: home
  namespace: code1
  labels:
    app: home
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: home

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: home-ingress
  namespace: code1
  labels:
    app: home
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/rewrite-target: '/'
spec:
  rules:
  - http:
      paths:
      - path: /code1/home
        backend:
          serviceName: home
          servicePort: http