apiVersion: v1
kind: ConfigMap
metadata:
  name: proj1-config
  namespace: code1
data:
  API_PATH_BASE: code1/proj1
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj1
  namespace: code1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proj1
  template:
    metadata:
      labels:
        app: proj1
    spec:
      containers:
      - name: code1-proj1
        image: tboeker/code1-proj1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: proj1-config
        - configMapRef:
            name: code1-config

---

apiVersion: v1
kind: Service
metadata:
  name: proj1
  namespace: code1
  labels:
    HealthChecks: enabled
    app: proj1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: proj1

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proj1-ingress
  namespace: code1
  labels:
    app: proj1
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  - http:
      paths:
      - path: /code1/proj1
        backend:
          serviceName: proj1
          servicePort: http


