apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: code1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: code1-hello
        image: tboeker/code1-hello
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: code1
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: hello

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: code1
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/add-base-url: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: code1
    http:
      paths:
      - path: /hello
        backend:
          serviceName: hello
          servicePort: 80



