apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-ui-config
  namespace: code1
data:
  API_PATH_BASE: swagger
  SwaggerDocs__0__Name: proj1-test1
  SwaggerDocs__0__Url: /proj1/swagger/proj1-test1.json
  SwaggerDocs__1__Name: proj1-test2
  SwaggerDocs__1__Url: /proj1/swagger/proj1-test2.json
  SwaggerDocs__2__Name: proj1-lifetime
  SwaggerDocs__2__Url: /proj1/swagger/proj1-lifetime.json
  SwaggerDocs__3__Name: proj2
  SwaggerDocs__3__Url: /proj2/swagger/proj2.json
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: code1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swaggerui
        image: tboeker/code1-swagger-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: swagger-ui-config
        - configMapRef:
            name: code1-config

---

apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
  namespace: code1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: swagger-ui

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swagger-ui-ingress
  namespace: code1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: code1
    http:
      paths:
      - path: /swagger
        backend:
          serviceName: swagger-ui
          servicePort: http



