apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "code1.fullname" . }}
  labels:
    {{- include "code1.labels" . | nindent 4 }}
data:   
  MongoDb__Server: {{ .Values.mongoDb.server }}
  EventStore__IpEndPoint: {{ .Values.eventStore.ipEndpoint }}
  