apiVersion: v1
kind: ConfigMap
metadata:
  name: health-ui-config
  namespace: code1
data:
  API_PATH_BASE: app/health
  ui_path: /app/health
  ui_api_path: /app/health/healthchecks-api
  ui_webhooks_path: /app/health-ui/healthchecks-webhooks
  ui_resources_path: /app/health/ui/resources
  ui_no_relative_paths: 'true'
  HealthChecksUI__HealthChecks__0__Name: proj1
  HealthChecksUI__HealthChecks__0__Uri: http://proj1/healthz
  HealthChecksUI__HealthChecks__1__Name: proj2
  HealthChecksUI__HealthChecks__1__Uri: http://proj2/healthz
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-ui
  namespace: code1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-ui
  template:
    metadata:
      labels:
        app: health-ui
    spec:
      containers:
      - name: healthchecksui
        image: xabarilcoding/healthchecksui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: health-ui-config
        - configMapRef:
            name: code1-config
---

apiVersion: v1
kind: Service
metadata:
  name: health-ui
  namespace: code1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: health-ui

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: health-ui-ingress
  namespace: code1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: code1
    http:
      paths:
      - path: /app/health
        backend:
          serviceName: health-ui
          servicePort: http



