parameters:
  - name: VariablesFile1
    type: string
    default: 'variables.yml'
  
  - name: VariablesFile2
    type: string
    default: 'variables-root-dev.yml'
  
  - name: CommandOptions
    type: string
    default: ''

  - name: WorkingDirectory
    type: string
    default: 'dev'

  - name: StageName
    type: string
    default: 'Stage1'
  
  - name: StageCondition
    type: object
    default: succeeded()
   
  - name: Env
    type: object
    default: {}
  
stages:
  - stage: ${{ parameters.StageName }}
    condition: ${{ parameters.StageCondition }}

    variables:

    - template: '${{ parameters.VariablesFile1 }}'
    - template: '${{ parameters.VariablesFile2 }}'

    displayName: ${{ variables.EnvironmentName }}
    jobs:

    - job: test_job
      pool:
        vmImage: 'ubuntu-latest'
      displayName: Test Stuff
      steps:
        - checkout: none

        - task: printAllVariables@1
      
        - script: echo '${{ variables.TF_VAR_EVENTSTORE_YODA_PASSWORD }}' $(TF_VAR_EVENTSTORE_YODA_PASSWORD)
          # env: 
          #   $[ parameters['Env'] ]

        